config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root 'home#index'

  # AJAX
  get 'busca_cep', :to => 'ajax#busca_cep', :as => 'busca_cep'
  
  resources :admin_users
  post 'create_admin_user', :to => 'admin_users#create', :as => 'create_admin_user'
  get 'users/:id/:step_number', :to => 'users#edit', :as => 'user_step'

  # Login
  resources :sessions
  # Logout
  get 'log_out', :to => 'sessions#destroy', :as => 'log_out'

  resources :users
  get 'activate_account/:activation_token', :to => 'users#activate_account', :as => 'activate_account'

  # View
  get 'recovery_pass', :to => 'users#recovery_pass', :as => 'recovery_pass'
  get 'edit_pass', :to => 'users#edit_pass', :as => 'edit_pass'

  post 'recovery_pass', :to => 'users#create_recovery_pass', :as => 'create_recovery_pass'
  get 'edit_pass/:recovery_token', :to => 'users#edit_pass', :as => 'edit_pass_token'
  patch 'update_pass/:id', :to => 'users#update_pass', :as => 'update_pass'
	
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :skip_validate_pass
  attr_accessor :step

  belongs_to :state
  belongs_to :city
  belongs_to :profile
  belongs_to :civil_state
  belongs_to :nationality
  belongs_to :graduation
  belongs_to :bank

  validates :email, :email => true

  has_secure_password

  validates_presence_of :name, :email, :profile_id

  belongs_to :company_city, :class_name => 'City'

  belongs_to :consultant, :class_name => 'User'

  has_many :users, :foreign_key => 'consultant_id'

  has_and_belongs_to_many :investment_answers
  has_and_belongs_to_many :objectives

  validates :email, :email => true, :uniqueness => true

  validates_length_of :password, :minimum => 6, if: Proc.new { |user| user.skip_validate_pass != true }

  # --- Conditional Validation --- #

  #Step 1
  validates_presence_of :email_secondary, 
    :celphone, 
    :birthday, 
    :civil_state_id, 
    :nationality_id, 
    :profession,
    :cpf,
    :rg,
    :issuer,
    :zip_code,
    :street,
    :state_id,
    :city_id,
    :district, if: Proc.new { |user| user.step.to_i == 1 }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	skip_before_filter :authenticate_user, :except => [:index, :edit, :update]

  def activate_account
    @user = User.find_by_activation_token params[:activation_token]
    if @user
      @user.update_column(:is_activated, true)
      session[:user_id] = @user.id
      gflash :success => "Acesso validado com sucesso"
      redirect_to new_user_path
    end
  end

  def new
  	@user = User.new
  end

  def edit
    @user = User.find params[:id]
    # Todas perguntas de perfil do investidor
    @investiment_questions = InvestmentQuestion.all
  end

  def update
    @user = User.find params[:id]
    @user.step = user_params[:step]
    @user.skip_validate_pass = true
    step = user_params[:step]

    if @user.update(user_params)

      gflash :success

      redirect_to user_step_path(@user, step.to_i + 1)

    else

      gflash :now, :error => @user.errors.full_messages.join('<br>')
      render :edit

    end
  end

  def create
  	@user = User.new user_params

    # Define o user como cliente
    @user.profile_id = 3

    @user.activation_token = SecureRandom.urlsafe_base64
    if @user.save
      # Envia email para usuário ativar seu cadastro
      ApplicationMailer.new_user_message(@user).deliver_now
      gflash :success => "Seu cadastro foi realizado, mas para sua segurança, solicitamos que acesse a conta de e-mail cadastrada e acesse o link para validação de seus dados. Obrigado!"
      redirect_to new_session_path
    else
      gflash :now, :error => @user.errors.full_messages.join('<br>')
      render 'new'
    end
  end

  def create_recovery_pass
  	user = User.find_by_email params[:email]

  	if user

  		user.update_column(:recovery_token, SecureRandom.urlsafe_base64)
  		ApplicationMailer.recovery_pass_message(user).deliver_now
  		gflash :success => "Verifique em seu email sua nova senha"
      redirect_to new_session_path

  	else

  		gflash :now, :error => "Email não encontrado"
      render 'recovery_pass'

  	end
  end

  def edit_pass
  	if params[:recovery_token]
      # efetua logoff para evitar de alterar senha do user logado
      session[:user_id] = nil
  		@user = User.find_by_recovery_token params[:recovery_token]
  	end

  	if current_user
			@user = current_user
  	end

  	if !@user
  		gflash :error => "Usuário não encontrado"
      redirect_to root_path
  	end
  end

  def update_pass
  	@user = User.find params[:id]
  	if @user.update_attributes(user_params)
  		# Autentica o user
  		session[:user_id] = @user.id

  		gflash :success
  		redirect_to root_path
  	else
  		gflash :error => @user.errors.full_messages.join('<br>')
      redirect_to edit_pass_path @user
  	end
  end

  private
  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :consultant_id,
      :email_secondary,
      :phone,
      :celphone,
      :birthday,
      :civil_state_id,
      :nationality_id,
      :profession,
      :zip_code,
      :district,
      :street,
      :state_id,
      :city_id,
      :complement,
      :cpf,
      :rg,
      :issuer,
      :step
    )
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_datagrid_actions.html.erb
<%= link_to "Editar", edit_user_path(object), :class => "btn btn-success"%>
<%= link_to "Excluir", edit_user_path(object), :class => "btn btn-danger", :"data-confirm" => 'Tem certeza que deseja excluir', :method => :delete %>

app/views/users/_edit_pass_form.html.erb
<%= simple_form_for @user, :url => update_pass_path(@user), defaults: { input_html: {class: 'form-control'}} do |f| %>
	<fieldset>
		<div class="row" >
			<div class="col-xs-12 ">
				<div class="form-group">
					<div class="input-group">
						<span class="input-group-addon">
							<i class="glyphicon glyphicon-lock"></i>
						</span>
						<%= f.input :password, label: false, :placeholder => 'Senha' %>
					</div>
				</div>
				<div class="form-group">
					<div class="input-group">
						<span class="input-group-addon">
							<i class="glyphicon glyphicon-lock"></i>
						</span>
  					<%= f.input :password_confirmation, label: false, :placeholder => 'Confirmação de senha' %>
					</div>
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-lg btn-primary btn-block" >Enviar</button>
				</div>
			</div>
		</div>
	</fieldset>
<% end %>

app/views/users/_step1.html.erb
<%= simple_form_for @user, defaults: { input_html: {class: 'form-control'}} do |f| %>
  <%= hidden_field_tag "user[step]", 1 %>
  <%= hidden_field_tag "step_number", params[:step_number] %>
  <br>
  <div role="tabpanel" class="tab-pane active" id="user-1">
    <div class="row">

      <!-- lado esquerdo -->
      <div id="step1-left" class="col-xs-6">

        <!-- perfil -->
        <% if @current_user.profile_id == 1 %>
          <div class="form-group">
            <label for="">Planejador:</label>
            <%= f.association :consultant, label: false%>
          </div>
        <%end%>

        <div class="form-group">
          <label for="">Email*</label>
          <%= f.input :email, label: false %>
        </div>

        <div class="form-group">
          <label for="">Email Secundário*</label>
          <%= f.input :email_secondary, label: false %>
        </div>

        <div class="form-group">
          <label for="">Nome Completo*</label>
          <%= f.input :name, label: false %>
        </div>

        <!-- CPF + RG -->
        <div class="pf-fields">
          <!-- CPF -->
          <div class="form-group">
            <label for="">CPF*</label>
            <%= f.input :cpf, label: false, input_html: {class: "form-control cpf"} %>
          </div>

          <!-- RG -->
          <div class="form-group">
            <label for="">RG*</label>
            <%= f.input :rg, label: false, placeholder: '99999-999' %>
          </div>

          <div class="form-group">
            <label for="">Orgão emissor*</label>
            <%= f.input :issuer, label: false%>
          </div>

        </div>

        <!-- telefone -->
        <div class="form-group">
          <label for="">Telefone</label>
          <%= f.input :phone, label: false, input_html: {class: "form-control phone"} %>
        </div>

        <div class="form-group">
          <label for="">Celular*</label>
          <%= f.input :celphone, label: false, input_html: {class: "form-control celphone"} %>
        </div>

      </div>

      <div id="step1-right" class="col-xs-6" style="margin-top:180px;">

        <div class="form-group">
          <label for="">Data de nascimento*</label>
          <%= f.text_field :birthday, label: false, class: "form-control date_filter", :value => f.object.birthday ? l( f.object.birthday) : nil%>
        </div>

        <div class="form-group">
          <label for="">Estado civil*</label>
          <%= f.association :civil_state, label: false%>
        </div>

        <div class="form-group">
          <label for="">Nacionalidade*</label>
          <%= f.association :nationality, label: false%>
        </div>

        <div class="form-group">
          <label for="">Profissão*</label>
          <%= f.input :profession, label: false%>
        </div>

        <!-- CEP -->
        <div class="form-group">
          <label for="">CEP*</label>
          <%= f.input :zip_code, label: false, input_html: {class: "form-control cep"} %>
        </div>

        <!-- endereço -->
        <div class="form-group">
          <label for="">Endereço*</label>
          <%= f.input :street, label: false, input_html: {autocomplete: false} %>
        </div>

        <div class="form-group">
          <label for="">Complemento</label>
          <%= f.input :complement, label: false%>
        </div>

        <div class="form-group">
          <label for="">Bairro*</label>
          <%= f.input :district, label: false%>
        </div>

        <!-- estado -->
        <div class="form-group">
          <label for="">Estado*</label>
          <%= f.association :state, label_method: :acronym, label: false %>
        </div>        

        <!-- cidade -->
        <div class="form-group">
          <label for="">Cidade*</label>
          <%= f.association :city, label: false %>
        </div>

        
      </div>

      <div class="col-xs-12">
        <% #if !@user.is_published %>
          <button type="submit" class="btn btn-primary pull-right">Salvar e ir para o próximo</button>
        <%# end %>
      </div>

    </div>
  </div>
<% end %>

app/views/users/_step2.html.erb
<%= simple_form_for @user, defaults: { input_html: {class: 'form-control'}} do |f| %>
  <%= hidden_field_tag "user[step]", 2 %>
  <%= hidden_field_tag "step_number", params[:step_number] %>
  <br>
  <div role="tabpanel" class="tab-pane active" id="user-1">
    <div class="row">

      <div class="form-group">
        <%= f.association :objectives,as: :check_boxes, label: false%>
      </div>

      <div class="col-xs-12">
          <button type="submit" class="btn btn-primary pull-right">Salvar e ir para o próximo</button>
          <a href="<%= user_step_path @current_user.id, 1 %>" class="btn btn-primary pull-left">Anterior</a>
      </div>

    </div>
  </div>
<% end %>

app/views/users/_step3.html.erb
<%= simple_form_for  @user, defaults: { input_html: {class: 'form-control'}} do |f| %>
  <%= hidden_field_tag "user[step]", 3 %>
  <%= hidden_field_tag "step_number", params[:step_number] %>
  <br>
  <div role="tabpanel" class="tab-pane active" id="user-1">
    <div class="row">

      <div class="form-group">
        <!-- Loop por cada pergunta de perfil de investidor -->
        <% @investiment_questions.each_with_index do |iq, index| %>
          <br><br>
          Questão - <%= index + 1 %>
          <br>
          <!-- Texto da pergunta -->
          <%= iq.question %>
          <!-- Possiveis respostas para a pergunta -->
          <%= f.association :investment_answers, label: false, as: :check_boxes, collection: InvestmentAnswer.where(:investment_question_id => iq.id), :label_method => lambda { |aq| aq.answer }, item_wrapper_class: "question_#{iq.id}" %>
        <% end %>
      </div>

      <div class="col-xs-12">
          <button type="submit" class="btn btn-primary pull-right">Salvar e ir para o próximo</button>
          <a href="<%= user_step_path @current_user.id, 2 %>" class="btn btn-primary pull-left">Anterior</a>
      </div>

    </div>
  </div>
<% end %>

app/views/users/_tabs.html.erb
<ul class="nav nav-tabs" role="tablist">

  <!-- Dados pessoais -->
  <li class="<%= 'active' if params[:step_number].to_i == 1 %>" role="presentation" class="active">
    <a href="<%= user_step_path @current_user.id, 1 %>" >Dados pessoais</a>
  </li>

  <!-- Objetivos -->
  <li class="<%= 'active' if params[:step_number].to_i == 2 %>" role="presentation">
    <a href="<%= user_step_path @current_user.id, 2 %>" >Objetivo</a>
  </li>

  <!-- Perfil de investidor -->
  <li class="<%= 'active' if params[:step_number].to_i == 3 %>" role="presentation">
    <a href="<%= user_step_path @current_user.id, 3 %>" >Perfil de investidor</a>
  </li>

  <!-- Dados complementares -->
  <li class="<%= 'active' if params[:step_number].to_i == 4 %>" role="presentation">
    <a href="<%= user_step_path @current_user.id, 4 %>" >Dados complementares</a>
  </li>

  <!-- senha de acesso -->
  <li class="<%= 'active' if params[:step_number].to_i == 5 %>" role="presentation">
    <a href="<%= user_step_path @current_user.id, 5 %>" >Senha de acesso</a>
  </li>


</ul>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Ficha de cadastro</h1>
    <div role="tabpanel">

      <%= render 'tabs' %>

      <!-- Tab panes -->
      <div class="tab-content">
        <% if params.has_key? :step_number %>
          <%= render "step#{params[:step_number]}" %>
        <% else %>
          <%= render 'step1' %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/users/edit_pass.html.erb
<div class="container">
	<div class="row" style="margin-top: 100px;">
		<div class="col-xs-4 col-xs-offset-4">

			<div class="panel panel-default">

				<div class="panel-heading text-center">
					<strong>Senha</strong>
				</div>
				<div class="panel-body">
					<%= render 'edit_pass_form' %>
				</div>
	    </div>

		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">

	<div class="row">
		<div class="col-xs-12">
			<h1>Usuários</h1>
		</div>
	</div>

	<div class="row">
		<% if @current_user.profile_id == 1%>
			<div class="col-xs-12">
					<a class="btn btn-primary pull-right" href="<%= new_user_path %>" role="button">
						Novo Usuário
					</a>
			</div>
		<%end%>
		<div class="col-xs-12">
			<%= datagrid_form_for @grid, :method => :get, :url => users_path %>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12">
			<%= datagrid_table @grid %>
			<%= paginate(@grid.assets) %>
		</div>
	</div>

</div>

app/views/users/new.html.erb
<div class="container">
	<div class="row" style="margin-top: 100px;">
		<div class="col-xs-4 col-xs-offset-4">

			<div class="panel panel-default">

				<div class="panel-heading text-center">
					<strong >Crie sua conta</strong>
				</div>

				<div class="panel-body">

					<%= simple_form_for @user, :defaults => { :input_html => { :class => 'form-control'}} do |f| %>

						<fieldset>
							<div class="row">
								<div class="col-xs-12 ">

									<div class="form-group">
										<div class="input-group">
											<span class="input-group-addon">A</span>
											<%= f.input :name, :label => false, :placeholder => 'Nome' %>
										</div>
									</div>

									<div class="form-group">
										<div class="input-group">
											<span class="input-group-addon">@</span>
											<%= f.input :email, :label => false, :placeholder => 'Email' %>
										</div>
									</div>

									<div class="form-group">
										<div class="input-group">
											<span class="input-group-addon">#</span>
											<%= f.input :password, :label => false, :placeholder => 'Senha' %>
										</div>
									</div>

									<div class="form-group">
										<div class="input-group">
											<span class="input-group-addon">#</span>
											<%= f.input :password_confirmation, :label => false, :placeholder => 'Confirmação de senha' %>
										</div>
									</div>
									<div class="form-group">
										<input type="submit" class="btn btn-lg btn-primary btn-block" value="Cadastrar">
									</div>
								</div>
							</div>
						</fieldset>
					<% end %>
				</div>

	    </div>

		</div>
	</div>
</div>

app/views/users/recovery_pass.html.erb
<div class="container">
	<div class="row" style="margin-top: 100px;">
		<div class="col-xs-4 col-xs-offset-4">

			<div class="panel panel-default">

				<div class="panel-heading text-center">
					<strong >Informe o email de acesso</strong>
				</div>
				<div class="panel-body">

					<%= form_tag create_recovery_pass_path %>
						<fieldset>
							<div class="row">
								<div class="col-xs-12 ">

									<div class="form-group">
										<div class="input-group">
											<span class="input-group-addon">@</span>
											<%= text_field_tag :email, params[:email], class: 'form-control' %>
										</div>
									</div>

									<div class="form-group">
										<input type="submit" class="btn btn-lg btn-primary btn-block" value="Enviar">
									</div>

								</div>
							</div>
						</fieldset>
					</form>

				</div>
	    </div>

		</div>
	</div>
</div>