config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root 'home#index'

  # AJAX
  get 'busca_cep', :to => 'ajax#busca_cep', :as => 'busca_cep'
  
  resources :admin_users
  post 'create_admin_user', :to => 'admin_users#create', :as => 'create_admin_user'
  get 'users/:id/:step_number', :to => 'users#edit', :as => 'user_step'

  # Login
  resources :sessions
  # Logout
  get 'log_out', :to => 'sessions#destroy', :as => 'log_out'

  resources :users
  get 'activate_account/:activation_token', :to => 'users#activate_account', :as => 'activate_account'

  # View
  get 'recovery_pass', :to => 'users#recovery_pass', :as => 'recovery_pass'
  get 'edit_pass', :to => 'users#edit_pass', :as => 'edit_pass'

  post 'recovery_pass', :to => 'users#create_recovery_pass', :as => 'create_recovery_pass'
  get 'edit_pass/:recovery_token', :to => 'users#edit_pass', :as => 'edit_pass_token'
  patch 'update_pass/:id', :to => 'users#update_pass', :as => 'update_pass'
	
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController

	before_filter :only_admin
  
  def index
  	@grid = UsersGrid.new(params[:users_grid]) do |scope|
			scope.page params[:page]
		end

    # Consultor e Status somente para Admin
		if @current_user.profile_id == 1

      @grid.column(:consultant, :html => true, :header => "Consultor") do |record|
		  	if record.consultant
		      record.consultant.name
		    end
		  end
		  @grid.column(:is_blocked, :html => true, :header => "Status")
		  @grid.column(:actions, :html => true) do |record|
        render "datagrid_actions", :object => record  
      end
    end
    
    # Coluna de editar apenas para Consultor
    if @current_user.profile_id == 2

      @grid.column(:actions, :html => true) do |record|
        render "datagrid_actions_edit", :object => record  
      end
    end

  end

  def new
  	@user = User.new
  end

  def edit
  	@user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    @user.skip_validate_pass = true
    if @user.update user_params
      gflash :success
      redirect_to admin_users_path
    else
      gflash :now, :error => @user.errors.full_messages.join('<br>')
      render :edit
    end
  end

  def destroy
    User.destroy params[:id]
    gflash :success => "Usuário excluído com sucesso"
    redirect_to admin_users_path
  end

  def create
  	@user = User.new user_params

    if @user.save
        @user.update_column(:is_activated, true)
        @user.update_column(:is_blocked, false)
        gflash :success
        redirect_to admin_users_path
    else
      gflash  :error => @user.errors.full_messages.join('<br>')
      render :new
    end
  end

  def user_params
    params.require(:user).permit(
      :is_blocked,
      :is_activated,
      :profile_id,
      :name,
      :email,
      :password,
      :password_confirmation
    )
  end


end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/_datagrid_actions.html.erb
<%= link_to "Editar", object.profile_id!=3 ? edit_admin_user_path(object) : user_step_path(object, 1), :class => "btn btn-success"%>
<%= link_to "Excluir", object.profile_id!=2 ? admin_user_path(object) : user_path(object), :class => "btn btn-danger", :"data-confirm" => 'Tem certeza que deseja excluir', :method => :delete %>

app/views/admin_users/_datagrid_actions_edit.html.erb
<%= link_to "Editar", edit_user_path(object), :class => "btn btn-success"%>

app/views/admin_users/_form.html.erb
<%= simple_form_for @user, :url => path, defaults: { input_html: {class: 'form-control'}} do |f| %>
  
  <div class="col-xs-6">

    <%= f.input :is_blocked, :label => "Bloqueado?" %>
  	<div class="form-group">
      <label for="">Perfil*</label>
      <%= f.association :profile, :collection => Profile.where.not(:id => 3), label: false, :include_blank => '-- Selecione um perfil --'  %>
    </div>

  	<div class="form-group">
      <label for="">Nome*</label>
      <%= f.input :name, label: false %>
    </div>

  	<div class="form-group">
      <label for="">Email*</label>
      <%= f.input :email, label: false %>
    </div>

    <%if @user.id == nil%>
      <div class="form-group">
        <label for="">Senha*</label>
        <%= f.input :password, label: false, input_html: { class: 'form-control wysiwyg' } %>
      </div>
    <%end%>

  </div>

  <div class="col-xs-12">


    <div class="form-group">
      <button type="submit" class="btn btn-primary pull-right">Salvar</button>
    </div>

  </div>

<% end %>

app/views/admin_users/create.html.erb
<h1>AdminUsers#create</h1>
<p>Find me in app/views/admin_users/create.html.erb</p>

app/views/admin_users/edit.html.erb
<h1>AdminUsers#edit</h1>
<p>Find me in app/views/admin_users/edit.html.erb</p>

app/views/admin_users/index.html.erb
<div class="container">

	<div class="row">
		<div class="col-xs-12">
			<h1>Usuários</h1>
		</div>
	</div>

	<div class="row">
		<% if @current_user.profile_id == 1%>
			<div class="col-xs-12">
					<a class="btn btn-primary pull-right" href="<%= new_user_path %>" role="button">
						Novo Usuário
					</a>
			</div>
		<%end%>
		<div class="col-xs-12">
			<%= datagrid_form_for @grid, :method => :get, :url => admin_users_path %>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12">
			<%= datagrid_table @grid %>
			<%= paginate(@grid.assets) %>
		</div>
	</div>

</div>

app/views/admin_users/new.html.erb
<div class="container">

  <div class="row">
    <div class="col-xs-12">
      <h1>Cadastrar Usuário</h1>
    </div>
  </div>

  <div class="row">
		<%= render 'form', :path => create_admin_user_path %>
  </div>

</div>