config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root 'home#index'

  # AJAX
  get 'busca_cep', :to => 'ajax#busca_cep', :as => 'busca_cep'
  
  resources :admin_users
  post 'create_admin_user', :to => 'admin_users#create', :as => 'create_admin_user'
  get 'users/:id/:step_number', :to => 'users#edit', :as => 'user_step'

  # Login
  resources :sessions
  # Logout
  get 'log_out', :to => 'sessions#destroy', :as => 'log_out'

  resources :users
  get 'activate_account/:activation_token', :to => 'users#activate_account', :as => 'activate_account'

  # View
  get 'recovery_pass', :to => 'users#recovery_pass', :as => 'recovery_pass'
  get 'edit_pass', :to => 'users#edit_pass', :as => 'edit_pass'

  post 'recovery_pass', :to => 'users#create_recovery_pass', :as => 'create_recovery_pass'
  get 'edit_pass/:recovery_token', :to => 'users#edit_pass', :as => 'edit_pass_token'
  patch 'update_pass/:id', :to => 'users#update_pass', :as => 'update_pass'
	
end

app/models/bank.rb
class Bank < ActiveRecord::Base

	has_many :users
	validates_presence_of :name
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
  has_many :users
  has_many :users, :foreign_key => 'company_city_id'

  validates_presence_of :name


end

app/models/civil_state.rb
class CivilState < ActiveRecord::Base

	has_many :users
	validates_presence_of :name

end

app/models/graduation.rb
class Graduation < ActiveRecord::Base

	has_many :users
	validates_presence_of :name

end

app/models/investment_answer.rb
class InvestmentAnswer < ActiveRecord::Base
  belongs_to :investment_question

  validates_presence_of :answer

  has_and_belongs_to_many :users

end

app/models/investment_question.rb
class InvestmentQuestion < ActiveRecord::Base

	validates_presence_of :question
	has_many :investment_answers

end

app/models/nationality.rb
class Nationality < ActiveRecord::Base

	has_many :users
	validates_presence_of :name

end

app/models/objective.rb
class Objective < ActiveRecord::Base

	validates_presence_of :name
	has_and_belongs_to_many :users

end

app/models/profile.rb
class Profile < ActiveRecord::Base

	has_many :users
	validates_presence_of :name
	

end

app/models/state.rb
class State < ActiveRecord::Base

	has_many :cities
	has_many :users
	has_many :users, :foreign_key => 'company_state_id'
	validates_presence_of :name



end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :skip_validate_pass
  attr_accessor :step

  belongs_to :state
  belongs_to :city
  belongs_to :profile
  belongs_to :civil_state
  belongs_to :nationality
  belongs_to :graduation
  belongs_to :bank

  validates :email, :email => true

  has_secure_password

  validates_presence_of :name, :email, :profile_id

  belongs_to :company_city, :class_name => 'City'

  belongs_to :consultant, :class_name => 'User'

  has_many :users, :foreign_key => 'consultant_id'

  has_and_belongs_to_many :investment_answers
  has_and_belongs_to_many :objectives

  validates :email, :email => true, :uniqueness => true

  validates_length_of :password, :minimum => 6, if: Proc.new { |user| user.skip_validate_pass != true }

  # --- Conditional Validation --- #

  #Step 1
  validates_presence_of :email_secondary, 
    :celphone, 
    :birthday, 
    :civil_state_id, 
    :nationality_id, 
    :profession,
    :cpf,
    :rg,
    :issuer,
    :zip_code,
    :street,
    :state_id,
    :city_id,
    :district, if: Proc.new { |user| user.step.to_i == 1 }

end

app/controllers/ajax_controller.rb
class AjaxController < ApplicationController
	def busca_cep
		require 'correios-cep'
		  address = Correios::CEP::AddressFinder.get(params[:cep])
		  data = {
	      :address => address
	    }

	    # Encaminha a resposta
	    respond_to do |format|
	      format.json {render :json => data, :status => 200}
	    end
		
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	skip_before_filter :authenticate_user
  
  def new
  end

  def create
  	user = User.find_by_email params[:email]
  	if user && user.authenticate(params[:password])

  		if user.is_blocked || !user.is_activated

  			if user.is_blocked
          gflash :now, :error => "Usuário bloqueado"
        else
          gflash :error => "Usuário inativado"
        end
        render "new" 

  		else	
	  		session[:user_id] = user.id

        #not is client
        if user.profile_id != 3

				  gflash :success => "Bem-vindo!"
  	  		redirect_to admin_users_path

        else

          gflash :success => "Bem-vindo!"
          #verificar rota correta
          redirect_to user_step_path(user.id, 1)

        end

	  	end
  			
  	else
  		gflash :now, :error => "Usuário não encontrado"
      render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	gflash :success => "Até logo"
  	redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	skip_before_filter :authenticate_user, :except => [:index, :edit, :update]

  def activate_account
    @user = User.find_by_activation_token params[:activation_token]
    if @user
      @user.update_column(:is_activated, true)
      session[:user_id] = @user.id
      gflash :success => "Acesso validado com sucesso"
      redirect_to new_user_path
    end
  end

  def new
  	@user = User.new
  end

  def edit
    @user = User.find params[:id]
    # Todas perguntas de perfil do investidor
    @investiment_questions = InvestmentQuestion.all
  end

  def update
    @user = User.find params[:id]
    @user.step = user_params[:step]
    @user.skip_validate_pass = true
    step = user_params[:step]

    if @user.update(user_params)

      gflash :success

      redirect_to user_step_path(@user, step.to_i + 1)

    else

      gflash :now, :error => @user.errors.full_messages.join('<br>')
      render :edit

    end
  end

  def create
  	@user = User.new user_params

    # Define o user como cliente
    @user.profile_id = 3

    @user.activation_token = SecureRandom.urlsafe_base64
    if @user.save
      # Envia email para usuário ativar seu cadastro
      ApplicationMailer.new_user_message(@user).deliver_now
      gflash :success => "Seu cadastro foi realizado, mas para sua segurança, solicitamos que acesse a conta de e-mail cadastrada e acesse o link para validação de seus dados. Obrigado!"
      redirect_to new_session_path
    else
      gflash :now, :error => @user.errors.full_messages.join('<br>')
      render 'new'
    end
  end

  def create_recovery_pass
  	user = User.find_by_email params[:email]

  	if user

  		user.update_column(:recovery_token, SecureRandom.urlsafe_base64)
  		ApplicationMailer.recovery_pass_message(user).deliver_now
  		gflash :success => "Verifique em seu email sua nova senha"
      redirect_to new_session_path

  	else

  		gflash :now, :error => "Email não encontrado"
      render 'recovery_pass'

  	end
  end

  def edit_pass
  	if params[:recovery_token]
      # efetua logoff para evitar de alterar senha do user logado
      session[:user_id] = nil
  		@user = User.find_by_recovery_token params[:recovery_token]
  	end

  	if current_user
			@user = current_user
  	end

  	if !@user
  		gflash :error => "Usuário não encontrado"
      redirect_to root_path
  	end
  end

  def update_pass
  	@user = User.find params[:id]
  	if @user.update_attributes(user_params)
  		# Autentica o user
  		session[:user_id] = @user.id

  		gflash :success
  		redirect_to root_path
  	else
  		gflash :error => @user.errors.full_messages.join('<br>')
      redirect_to edit_pass_path @user
  	end
  end

  private
  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :consultant_id,
      :email_secondary,
      :phone,
      :celphone,
      :birthday,
      :civil_state_id,
      :nationality_id,
      :profession,
      :zip_code,
      :district,
      :street,
      :state_id,
      :city_id,
      :complement,
      :cpf,
      :rg,
      :issuer,
      :step
    )
  end

end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/datagrid/_enum_checkboxes.html.erb
<%# 
Indent in this file may cause extra space to appear.
You can add indent if whitespace doesn't matter for you
%>
<%- elements.each do |value, text, checked| -%>
<%- id = [form.object_name, filter.name, value].join('_').underscore -%>
<%= form.label filter.name, options.merge(:for => id) do -%>
<%= form.check_box(filter.name, form.datagrid_extra_checkbox_options.merge(:multiple => true, :id => id, :checked => checked), value.to_s, nil) -%>
<%= text -%>
<%- end -%>
<%- end -%>

app/views/datagrid/_form.html.erb
<%= form_for grid, options do |f| -%>
  <% grid.filters.each do |filter| %>
  <!-- Verifica se existe alguma condição para exibir o filtro -->
    <% if !filter.options[:reject_if] || ! eval(filter.options[:reject_if]) %>
      <div class="datagrid-filter filter">
        <%= f.datagrid_label filter %>
        <%= f.datagrid_filter filter, partials: options[:partials] %>
      </div>
    <% end %>
  <% end %>
  <div class="datagrid-actions">
    <%= f.submit I18n.t("datagrid.form.search").html_safe, :class => "datagrid-submit" %>
    <%# https://github.com/rails/rails/pull/14949 -%>
    <% empty_parameter = Rails.version >= "4.1.0" && Rails.version <= '4.1.2' ? nil : {}-%>
    <%= link_to I18n.t('datagrid.form.reset').html_safe, url_for(grid.to_param => empty_parameter), :class => "datagrid-reset" %>
  </div>
<% end -%>

app/views/datagrid/_head.html.erb
<tr>
  <% grid.html_columns(*options[:columns]).each do |column| %>
    <th class="<%= datagrid_column_classes(grid, column) %>">
      <%= column.header %>
      <%= datagrid_order_for(grid, column, options) if column.supports_order? && options[:order]%>
    </th>
  <% end %>
</tr>

app/views/datagrid/_order_for.html.erb
<div class="order">
  <%= link_to(
      I18n.t("datagrid.table.order.asc").html_safe,
      url_for(grid.param_name => grid.as_query.merge(:order => column.name, :descending => false)),
      :class => "asc") %>
  <%= link_to(
      I18n.t("datagrid.table.order.desc").html_safe,
      url_for(grid.param_name => grid.as_query.merge(:order => column.name, :descending => true )),
      :class => "desc") %>
</div>

app/views/datagrid/_range_filter.html.erb
<%= form.text_field(filter.name, from_options) %>
<span class="separator <%= filter.type %>"> - </span>
<%= form.text_field(filter.name, to_options) %>

app/views/datagrid/_row.html.erb
<tr class="<%= options[:cycle] && cycle(*options[:cycle]) %>">
  <% grid.html_columns(*options[:columns]).each do |column| %>
    <td class="<%= datagrid_column_classes(grid, column) %>"><%= datagrid_value(grid, column, asset) %></td>
  <% end %>
</tr>

app/views/datagrid/_table.html.erb
<%#
Local variables:
* grid - instance of Datagrid
* assets - Array of database Entities
* options - passed options Hash
%>
<%= content_tag :table, options[:html] do %>
  <thead>
    <%= datagrid_header(grid, options) %>
  </thead>
  <tbody>
    <% if assets.any? %>
      <%= datagrid_rows(grid, assets, options) %>
    <% else %>
      <tr><td class="noresults" colspan="100%"><%= I18n.t('datagrid.no_results').html_safe %></td></tr>
    <% end %>
  </tbody>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<% if @current_user %>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="<%= root_path %>">
          Logo
        </a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li>
            <a  href="<%= root_path%>">Home</a>
          </li>
          <!-- Cliente -->
          <% if @current_user == 3 %>
            <li>
              <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Ficha cadastro<span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="<%= user_step_path(@current_user, 1)%>">Dados Pessoais</a>
                </li>
                <li>
                  <a href="<%= user_step_path(@current_user, 2)%>">Objetivo</a>
                </li>
                <li>
                  <a href="<%= user_step_path(@current_user, 3)%>">Perfil de investidor</a>
                </li>
                <li>
                  <a href="<%= user_step_path(@current_user, 4)%>">Dados Complementares</a>
                </li>
                <li>
                  <a href="<%= user_step_path(@current_user, 5)%>">Senha de Acesso</a>
                </li>
              </ul>
            </li>
          <%end%>

          <li>
            <a  href="<%= root_path%>">Perfil</a>
          </li>

        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="<%= log_out_path %>">Sair</a>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
  </nav>
<% end %>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wgfp" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Wgfp" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.css" rel="stylesheet">

    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= gflash %>
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.3.1/jquery.maskedinput.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/locales/bootstrap-datepicker.pt-BR.js"></script>
  </body>
</html>